apiVersion: "2019-12-01"
location: US East
name: gpt-telegram-bot
type: Microsoft.ContainerInstance/containerGroups
properties:
  osType: Linux
  restartPolicy: Always
  containers:
    - name: mongo
      properties:
        image: gptbot.azurecr.io/mongo
        restart: always
        resources:
          requests:
            cpu: 1
            memoryInGB: 1
        ports:
          - protocol: tcp
            port: 27017
        volumes:
          - ${MONGODB_PATH:-./mongodb}:/data/db
        environmentVariables:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: <MONGODB_USERNAME>
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: <MONGODB_PASSWORD>

    - name: gpt-telegram-bot
      properties:
        image: gptbot.azurecr.io/gpt-telegram-bot
        resources:
          requests:
            cpu: 1
            memoryInGB: 1
        ports:
          - protocol: tcp
            port: 80
        command: python3 bot/bot.py
        restart: always
        build:
          context: "."
          dockerfile: Dockerfile
        depends_on:
          - mongo
        environmentVariables:
    - name: mongo-express
      properties:
        image: gptbot.azurecr.io/mongo-express
        resources:
          requests:
            cpu: 1
            memoryInGB: 1
        ports:
          - protocol: tcp
            port: 8081
        environmentVariables:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: <MONGODB_USERNAME>
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: <MONGODB_PASSWORD>
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongo
  imageRegistryCredentials:
    - server: gptbot.azurecr.io
      username: gptbot
      password: qULn7rH0uCzYKZMwl1DI7UvTTO1qx+fRwlQ5fYQxtg+ACRAzwhJ7
