version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - ${gptbotstorage:-./mongodb}:/data/db
    gptbotstorage:
      driver: azure_file
      driver_opts:
        share_name: gptbotfileshare
        storage_account_name: gptbotstorage
        storage_account_key: rJf7gSSVh3LahF1QITwDiGjuFQiLwJ6IpYMd7mte/vxqbBOj8SOWsTxJoqBYIgw0tqSjNWkLhLsi+AStip8Z9A==
        connection_string: DefaultEndpointsProtocol=https;AccountName=gptbotstorage;AccountKey=rJf7gSSVh3LahF1QITwDiGjuFQiLwJ6IpYMd7mte/vxqbBOj8SOWsTxJoqBYIgw0tqSjNWkLhLsi+AStip8Z9A==;EndpointSuffix=core.windows.net
        fuck: https://gptbotstorage.file.core.windows.net/gptbotfil
    # TODO: add auth

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    image: gptbot.azurecr.io/chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo

  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo
